<<<<<<< HEAD

// const Root = url => `http://64.202.184.112:5000/api/${url}`;  //live

=======
>>>>>>> 1efb17fd4e6918320511e82874706b886d9fece0
const Root = url => `http://64.202.184.112:5000/api/${url}`;  //local


class Api {
    static login = Root('AuthAPI/Login');
    static GetAllRecordsCurrent = Root('JobsAPI/GetAllRecords');
<<<<<<< HEAD
    static GetAllRecordsJob = Root('JobsAssignmentAPI/GetAllRecords');
    static GetCommentAndFeedback= Root('CommentsAndFeedback/GetAllRecords');
    static GetSupCompletedJobs= Root('JobsAPI/GetAllRecords')
    static GetSupActiveJobs= Root('JobsAssignmentAPI/ActiveJobDetail')
    static GetSupNotification = Root('Notification/GetAllRecords')
    static GetJobAssignment = Root('JobsAssignmentAPI/JobAssignDetail')
    static GetFeedbackType = Root('GlobalCodeAPI/GetAllRecords')
    static GetFeedbackPriority=Root('GlobalCodeAPI/GetAllRecords')
    static GetFeedbackCreate=Root('CommentsAndFeedback/Create')
    static TechnicianTypes=Root('GlobalCodeAPI/GetAllRecords');
    static JobAssigned=Root('JobsAssignmentAPI/CreateJobAssign');
    
    static jobInprogressDropDown=Root('GlobalCodeAPI/GetAllRecords');
    static markasreadNotification=Root('Notification/MarkAsRead');

    
  
// Technicians
static GetTechCommentAndFeedback= Root('CommentsAndFeedback/GetAllRecords');
static GetSTechNotification = Root('Notification/GetAllRecords')
static GetAllAttributes = Root('ObjectAttributesAPI/GetAllObjectAttributeRecords');
static JobDetails = Root('JobsAPI/GetAllRecords'); 

=======
<<<<<<< HEAD
    static GetJobByEquipmentId = Root('JobsAPI/GetJobByEquipmentId');
    static GetJobNoByEquipId = Root('JobsAPI/GetJobNumber');            //GetAutogeneratedJobCode if M/C id Available
    static GetAutoGenEquipId = Root('JobsAPI/GetJobNumber');           //GetAutogenerateEquipId & JobCode for M/C not Available
    static GetRecordsClientType = Root('GlobalCodeAPI/GetAllRecords'); // Client-Regular/Cash

=======
    static AdditionalHours = Root('AdditionalWorkRequest/Create');
    static forgotPassword = Root('UsersAPI/ForgotPassword');
    static verifyOTP = Root('UsersAPI/VerifyToken');
    static resetPassword = Root('UsersAPI/ResetPassword');
    static TechniciansTeamMembers = Root('JobActivityAPI/GetTechniciansTeamMembers');
    static TechnicianTypes = Root('GlobalCodeAPI/GetAllRecords');
    static ActiveJobDetail = Root('JobsAssignmentAPI/ActiveJobDetail');
    static TeamMembersupervisor = Root('JobsAssignmentAPI/ActiveJobMembers');
    static TechnicianDetail = Root('JobsAssignmentAPI/GetAllRecords');
    static GetJobByEquipmentId = Root('JobsAPI/GetJobByEquipmentId');
    static GetJobNoByEquipId = Root('JobsAPI/GetJobNumber');
    static GetAllAttributes = Root('ObjectAttributesAPI/GetAllObjectAttributeRecords');


    //GetAutogeneratedJobCode if M/C id Available
    static GetAutoGenEquipId = Root('JobsAPI/GetJobNumber');               //GetAutogenerateEquipId & JobCode for M/C not Available
    static GetRecordsClientType = Root('GlobalCodeAPI/GetAllRecords');      // Client-Regular/Cash
>>>>>>> cdc289e2804b5bc3c721f86018d5aca4d96f9fbc
    static GetSearchClientRecord = Root('ClientsAPI/SearchClientRecords'); //search Client
    static GetRecordsMachineType = Root('MachineTypeAPI/GetAllRecords');  //MachineTypeDropdown
    static GetAllRecordsMachine = Root('ManageMachineAPI/GetAllRecords'); //MachineDropdown
    static GetAllRecordsSegment = Root('SegmentAPI/GetAllRecords');       //SegmentDropdown
<<<<<<< HEAD
    static GetAllChooseJobType = Root('JobTypeAPI/GetAllRecords');       //ChooseJobtype
    static CreateJobClientType = Root('JobsAPI/Create');       //
    static GetTechnicianTypeLabel = Root('GlobalCodeAPI/GetAllRecords')  //TechniciantypeLabel
    static TechnicianDetail= Root('JobsAssignmentAPI/GetAllRecords');    
    static GetAllRecordsJob = Root('JobsAssignmentAPI/GetAllRecords'); //Job Assignment
    static GetAllAttributes = Root('ObjectAttributesAPI/GetAllObjectAttributeRecords'); //Attributes Api
    static jobInprogressDropDown=Root('GlobalCodeAPI/GetAllRecords');
    static IdentifycreateAttributeDetails=Root('ObjectAttributesAPI/CreateAttributeDetail');// Create AttributeDetails
    static JobDetails = Root('JobsAPI/GetAllRecords'); 
    static JobAssigned=Root('JobsAssignmentAPI/CreateJobAssign');
    static TechnicianTypes=Root('GlobalCodeAPI/GetAllRecords');
=======
    static GetAllChooseJobType = Root('JobTypeAPI/GetAllRecords');
    //ChooseJobtype
    static CreateJobClientType = Root('JobsAPI/Create');       //
    static GetTechnicianTypeLabel = Root('GlobalCodeAPI/GetAllRecords');    //TechniciantypeLabel



    static GetAllRecordsJob = Root('JobsAssignmentAPI/GetAllRecords');
    static GetCommentAndFeedback = Root('CommentsAndFeedback/GetAllRecords');
    static GetSupCompletedJobs = Root('JobsAPI/GetAllRecords');
    static GetSupActiveJobs = Root('JobsAssignmentAPI/ActiveJobDetail');
    static GetSupNotification = Root('Notification/GetAllRecords');
    static GetJobAssignment = Root('JobsAssignmentAPI/JobAssignDetail');
    static GetFeedbackType = Root('GlobalCodeAPI/GetAllRecords');
    static GetFeedbackPriority = Root('GlobalCodeAPI/GetAllRecords');
    static GetJobAssignment = Root('JobsAssignmentAPI/JobAssignDetail');
    static JobAssigned = Root('JobsAssignmentAPI/CreateJobAssign');
    static markasreadNotification = Root('Notification/MarkAsRead');


// Technicians
    static GetTechCommentAndFeedback = Root('CommentsAndFeedback/GetAllRecords');
    static GetSTechNotification = Root('Notification/GetAllRecords');
    static JobDetails = Root('JobsAPI/GetAllRecords');


>>>>>>> cdc289e2804b5bc3c721f86018d5aca4d96f9fbc
>>>>>>> 1efb17fd4e6918320511e82874706b886d9fece0
}

export default Api;



