// const Root = (url) => `https://medial-health.techpss.com/${url}`;   //live
//const Root = (url) => `https://medial-health.techpss.com/${url}`;   //live
///const Root = url => `http://192.168.0.65:4008/${url}`;  //local



// http://64.202.184.112:5000/api/AuthAPI/Login




const Root = url => `http://64.202.184.112:5000/api/${url}`;  //local


class Api {
    static login = Root('AuthAPI/Login');
    static GetAllRecordsCurrent = Root('JobsAPI/GetAllRecords');
    static AdditionalHours=Root('AdditionalWorkRequest/Create');
    static forgotPassword=Root('UsersAPI/ForgotPassword');
    static TechniciansTeamMembers=Root('JobActivityAPI/GetTechniciansTeamMembers');
    static TechnicianTypes=Root('GlobalCodeAPI/GetAllRecords');
   static ActiveJobDetail=Root('JobsAssignmentAPI/ActiveJobDetail');
   static TeamMembersupervisor=Root('JobsAssignmentAPI/ActiveJobMembers');
   static TechnicianDetail=Root('JobsAssignmentAPI/GetAllRecords');
   static GetJobByEquipmentId = Root('JobsAPI/GetJobByEquipmentId');
   static GetJobNoByEquipId = Root('JobsAPI/GetJobNumber'); 
   static GetAllAttributes = Root('ObjectAttributesAPI/GetAllObjectAttributeRecords');


    //GetAutogeneratedJobCode if M/C id Available
   static GetAutoGenEquipId = Root('JobsAPI/GetJobNumber');           //GetAutogenerateEquipId & JobCode for M/C not Available
   static GetRecordsClientType = Root('GlobalCodeAPI/GetAllRecords'); // Client-Regular/Cash
   static GetSearchClientRecord = Root('ClientsAPI/SearchClientRecords'); //search Client
   static GetRecordsMachineType = Root('MachineTypeAPI/GetAllRecords');  //MachineTypeDropdown
   static GetAllRecordsMachine = Root('ManageMachineAPI/GetAllRecords'); //MachineDropdown
   static GetAllRecordsSegment = Root('SegmentAPI/GetAllRecords');       //SegmentDropdown
   static GetAllChooseJobType = Root('JobTypeAPI/GetAllRecords');       //ChooseJobtype
   static CreateJobClientType = Root('JobsAPI/Create');       //
   static GetTechnicianTypeLabel = Root('GlobalCodeAPI/GetAllRecords')  //TechniciantypeLabel
   static jobInprogressDropDown=Root('GlobalCodeAPI/GetAllRecords');




   static GetAllRecordsJob = Root('JobsAssignmentAPI/GetAllRecords');
   static GetCommentAndFeedback= Root('CommentsAndFeedback/GetAllRecords');
   static GetSupCompletedJobs= Root('JobsAPI/GetAllRecords')
   static GetSupActiveJobs= Root('JobsAssignmentAPI/ActiveJobDetail')
   static GetSupNotification = Root('Notification/GetAllRecords')
   static GetJobAssignment = Root('JobsAssignmentAPI/JobAssignDetail')
   static GetFeedbackType = Root('GlobalCodeAPI/GetAllRecords')
   static GetFeedbackPriority=Root('GlobalCodeAPI/GetAllRecords')
   
 
// Technicians
static GetTechCommentAndFeedback= Root('CommentsAndFeedback/GetAllRecords');
static GetSTechNotification = Root('Notification/GetAllRecords')
static JobDetails = Root('JobsAPI/GetAllRecords'); 







}

export default Api;



