// const Root = (url) => `https://medial-health.techpss.com/${url}`;   //live
//const Root = (url) => `https://medial-health.techpss.com/${url}`;   //live
///const Root = url => `http://192.168.0.65:4008/${url}`;  //local



// http://64.202.184.112:5000/api/AuthAPI/Login




const Root = url => `http://64.202.184.112:5000/api/${url}`;  //local


class Api {
    static login = Root('AuthAPI/Login');
    static GetAllRecordsCurrent = Root('JobsAPI/GetAllRecords');
    static GetJobByEquipmentId = Root('JobsAPI/GetJobByEquipmentId');
    static GetJobNoByEquipId = Root('JobsAPI/GetJobNumber');            //GetAutogeneratedJobCode if M/C id Available
    static GetAutoGenEquipId = Root('JobsAPI/GetJobNumber');           //GetAutogenerateEquipId & JobCode for M/C not Available
    static GetRecordsClientType = Root('GlobalCodeAPI/GetAllRecords'); // Client-Regular/Cash

    static GetSearchClientRecord = Root('ClientsAPI/SearchClientRecords'); //search Client
    static GetRecordsMachineType = Root('MachineTypeAPI/GetAllRecords');  //MachineTypeDropdown
    static GetAllRecordsMachine = Root('ManageMachineAPI/GetAllRecords'); //MachineDropdown
    static GetAllRecordsSegment = Root('SegmentAPI/GetAllRecords');       //SegmentDropdown
    static GetAllChooseJobType = Root('JobTypeAPI/GetAllRecords');       //ChooseJobtype
    static CreateJobClientType = Root('JobsAPI/Create');       //
    static GetTechnicianTypeLabel = Root('GlobalCodeAPI/GetAllRecords')  //TechniciantypeLabel
    static TechnicianDetail= Root('JobsAssignmentAPI/GetAllRecords');    
    static GetAllRecordsJob = Root('JobsAssignmentAPI/GetAllRecords'); //Job Assignment
    static GetAllAttributes = Root('ObjectAttributesAPI/GetAllObjectAttributeRecords'); //Attributes Api
    static jobInprogressDropDown=Root('GlobalCodeAPI/GetAllRecords');
    static IdentifycreateAttributeDetails=Root('ObjectAttributesAPI/CreateAttributeDetail');// Create AttributeDetails
    static JobDetails = Root('JobsAPI/GetAllRecords'); 
    static JobAssigned=Root('JobsAssignmentAPI/CreateJobAssign');
    static TechnicianTypes=Root('GlobalCodeAPI/GetAllRecords');
}

export default Api;



