const Action = {
    PROGRESS: 'PROGRESS',
    SIGN_OUT: 'SIGN_OUT',
    PROFILE_DATA_APIRESPONSE: 'PROFILE_DATA_APIRESPONSE',
    VITAL_SCREEN_DATA: 'VITAL_SCREEN_DATA',
    IS_INTERNET_CONNECTED: 'IS_INTERNET_CONNECTED',

    HEALTH_DIARY_BOARD_DATA: 'HEALTH_DIARY_BOARD_DATA',
    HDA: {
        CURRENT_USER: 'CURRENT_USER',
        VITAL_TYPE: 'VITAL_TYPE',
        CURRENT_USER_PERMISSION_DATA: 'CURRENT_USER_PERMISSION_DATA',
        CURRENT_INDEX: 'CURRENT_INDEX',
        DESHBOARD: {
            API_UNDER_PROGRESS: 'DESHBOARD_API_UNDER_PROGRESS',
            API_DATE: 'DESHBOARD_API_DATE',
            API_FAIL: 'DESHBOARD_API_FAIL',
        },
        VITAL: {
            API_UNDER_PROGRESS: 'VITAL_API_UNDER_PROGRESS',
            API_DATA: 'VITAL_API_DATA',
            API_FAIL: 'VITAL_API_FAIL',
            DELETE_VITAL: 'DELETE_VITAL',
        }
        ,
        ALLERGIES: {
            API_UNDER_PROGRESS: 'ALLERGIES_API_UNDER_PROGRESS',
            ALLERGIES_API_DATE: 'ALLERGIES_ALLERGIES_API_DATE',
            ALLERGIES_API_FAIL: 'ALLERGIES_ALLERGIES_API_FAIL',
            REMOVE_ALLERGIS_ITEM: 'REMOVE_ALLERGIS_ITEM',
        },
        SYMPTOMS: {
            API_UNDER_PROGRESS: 'SYMPTOMS_API_UNDER_PROGRESS',
            API_DATA: 'SYMPTOMS_API_DATA',
            API_FAIL: 'SYMPTOMS_API_FAIL',
            DELETE_SYMPTOMS: 'DELETE_SYMPTOMS',
        },
        DIAGNOSIS: {
            API_UNDER_PROGRESS: 'DIAGNOSIS_API_UNDER_PROGRESS',
            API_DATA: 'DIAGNOSIS_API_DATA',
            API_FAIL: 'DIAGNOSIS_API_FAIL',
            DELETE_DIAGNOSIS: 'DELETE_DIAGNOSIS',
        },
        MEDICATIONS: {
            API_UNDER_PROGRESS: 'MEDICATIONS_API_UNDER_PROGRESS',
            API_DATA: 'MEDICATIONS_API_DATA',
            API_FAIL: 'MEDICATIONS_API_FAIL',
            DELETE_MEDICATIONS: 'DELETE_MEDICATIONS',
        },

    },
    HOME: {
        CURRENT_DASH_USER: 'CURRENT_DASH_USER',
        NOTIFICATION_STATUS: 'NOTIFICATION_STATUS',
        CURRENT_USER_PERMISSION_DATA: 'CURRENT_USER_PERMISSION_DATA',
        CURRENT_DASH_INDEX: 'CURRENT_DASH_INDEX',
  
        VITALLIST: {
            API_UNDER_PROGRESS: 'VITALLIST_API_UNDER_PROGRESS',
            API_DATA: 'VITALLIST_API_DATA',
            API_FAIL: 'VITALLIST_API_FAIL',
        },
        CURRENTLIST: {
            API_UNDER_PROGRESS: 'CURRENTLIST_API_UNDER_PROGRESS',
            API_DATA: 'CURRENTLIST_API_DATA',
            API_FAIL: 'CURRENTLIST_API_FAIL',
        }, TRENDLIST: {
            API_UNDER_PROGRESS: 'TRENDLIST_API_UNDER_PROGRESS',
            API_DATA: 'TRENDLIST_API_DATA',
            API_FAIL: 'TRENDLIST_API_FAIL',
        },
    },
    DOCTOR_APPOINTMENT: {
        API_UNDER_PROGRESS: 'DOCTOR_APPOINTMENT_API_UNDER_PROGRESS',
        API_DATA: 'DOCTOR_APPOINTMENT_API_DATA',
        API_FAIL: 'DOCTOR_APPOINTMENT_API_FAIL',
        REMOVE_ITEM: 'DOCTOR_REMOVE_ITEM',
    },
    DOCTOR: {
        API_UNDER_PROGRESS: 'DOCTOR_API_UNDER_PROGRESS',
        API_DATA: 'DOCTOR_API_DATA',
        API_FAIL: 'DOCTOR_API_FAIL',
        REMOVE_DOCTOR: 'DOCTOR_REMOVE_DOCTOR',
    },
    ALL_APPOINTMENT: {
        API_UNDER_PROGRESS: 'ALL_APPOINTMENT_API_UNDER_PROGRESS',
        API_DATA: 'ALL_APPOINTMENT_API_DATA',
        API_FAIL: 'ALL_APPOINTMENT_API_FAIL',
        REMOVE_ITEM: 'ALL_APPOINTMENT_REMOVE_ITEM',
    },
    SEARCH_ALL_APPOINTMENT: {
        UNDER_PROGRESS: 'SEARCH_ALL_APPOINTMENT_UNDER_PROGRESS',
        API_DATE: 'SEARCH_ALL_APPOINTMENT_API_DATE',
        API_FAIL: 'SEARCH_ALL_APPOINTMENT_API_FAIL',
    },
    RELATIONSHIP: {
        SHARED: {
            SENT: {
                API_UNDER_PROGRESS: 'RELATIONSHIP_SHARED_SENT_API_UNDER_PROGRESS',
                API_DATA: 'RELATIONSHIP_SHARED_SENT_API_DATA',
                API_FAIL: 'RELATIONSHIP_SHARED_SENT_API_FAIL',
            },
            RECIVED: {
                API_UNDER_PROGRESS: 'RELATIONSHIP_SHARED_RECIVED_API_UNDER_PROGRESS',
                API_DATA: 'RELATIONSHIP_SHARED_RECIVED_API_DATA',
                API_FAIL: 'RELATIONSHIP_SHARED_RECIVED_API_FAIL',
            },
        },
        REQUEST: {
            SENT: {
                API_UNDER_PROGRESS: 'RELATIONSHIP_REQUEST_SENT_API_UNDER_PROGRESS',
                API_DATA: 'RELATIONSHIP_REQUEST_SENT_API_DATA',
                API_FAIL: 'RELATIONSHIP_REQUEST_SENT_API_FAIL',
            },
            RECIVED: {
                API_UNDER_PROGRESS: 'RELATIONSHIP_REQUEST_RECIVED_API_UNDER_PROGRESS',
                API_DATA: 'RELATIONSHIP_REQUEST_RECIVED_API_DATA',
                API_FAIL: 'RELATIONSHIP_REQUEST_RECIVED_API_FAIL',
            },
        },
    },
    RELATION_LIST: {
        API_UNDER_PROGRESS: 'RELATION_LIST_API_UNDER_PROGRESS',
        API_DATA: 'RELATION_LIST_API_DATA',
        API_FAIL: 'RELATION_LIST_API_FAIL',
        COLOR_RELATION: 'COLOR_RELATION',
    },
    ALL_RELATION_LIST: {
        API_UNDER_PROGRESS: 'ALL_RELATION_LIST_API_UNDER_PROGRESS',
        API_DATA: 'ALL_RELATION_LIST_API_DATA',
        API_FAIL: 'ALL_RELATION_LIST_API_FAIL',
        REMOVE_RELATION: 'REMOVE_RELATION',
    },
    NOTIFICATION_LIST: {
        API_UNDER_PROGRESS: 'ALL_NOTIFICATION_LIST_API_UNDER_PROGRESS',
        API_DATA: 'ALL_NOTIFICATION_LIST_API_DATA',
        API_FAIL: 'ALL_NOTIFICATION_LIST_API_FAIL',
    },
};
export default Action;
